#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'onchip_memory2_0', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY2_0_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY2_0_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_COMPONENT_NAME onchip_memory2_0
#define ONCHIP_MEMORY2_0_BASE 0x0
#define ONCHIP_MEMORY2_0_SPAN 65536
#define ONCHIP_MEMORY2_0_END 0xffff
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE soc_system_onchip_memory2_0
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_0_INSTANCE_ID NONE
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 65536
#define ONCHIP_MEMORY2_0_WRITABLE 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_DATA_WIDTH 64
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory2_0

/*
 * Macros for device 'PIO_EMPTY', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_EMPTY_'.
 * The prefix is the slave descriptor.
 */
#define PIO_EMPTY_COMPONENT_TYPE altera_avalon_pio
#define PIO_EMPTY_COMPONENT_NAME PIO_EMPTY
#define PIO_EMPTY_BASE 0x0
#define PIO_EMPTY_SPAN 32
#define PIO_EMPTY_END 0x1f
#define PIO_EMPTY_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_EMPTY_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_EMPTY_CAPTURE 0
#define PIO_EMPTY_DATA_WIDTH 1
#define PIO_EMPTY_DO_TEST_BENCH_WIRING 0
#define PIO_EMPTY_DRIVEN_SIM_VALUE 0
#define PIO_EMPTY_EDGE_TYPE NONE
#define PIO_EMPTY_FREQ 50000000
#define PIO_EMPTY_HAS_IN 1
#define PIO_EMPTY_HAS_OUT 0
#define PIO_EMPTY_HAS_TRI 0
#define PIO_EMPTY_IRQ_TYPE NONE
#define PIO_EMPTY_RESET_VALUE 0

/*
 * Macros for device 'PIO_FULL', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_FULL_'.
 * The prefix is the slave descriptor.
 */
#define PIO_FULL_COMPONENT_TYPE altera_avalon_pio
#define PIO_FULL_COMPONENT_NAME PIO_FULL
#define PIO_FULL_BASE 0x10
#define PIO_FULL_SPAN 32
#define PIO_FULL_END 0x2f
#define PIO_FULL_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_FULL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_FULL_CAPTURE 0
#define PIO_FULL_DATA_WIDTH 1
#define PIO_FULL_DO_TEST_BENCH_WIRING 0
#define PIO_FULL_DRIVEN_SIM_VALUE 0
#define PIO_FULL_EDGE_TYPE NONE
#define PIO_FULL_FREQ 50000000
#define PIO_FULL_HAS_IN 1
#define PIO_FULL_HAS_OUT 0
#define PIO_FULL_HAS_TRI 0
#define PIO_FULL_IRQ_TYPE NONE
#define PIO_FULL_RESET_VALUE 0

/*
 * Macros for device 'PIO_DATA_OUT', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_DATA_OUT_'.
 * The prefix is the slave descriptor.
 */
#define PIO_DATA_OUT_COMPONENT_TYPE altera_avalon_pio
#define PIO_DATA_OUT_COMPONENT_NAME PIO_DATA_OUT
#define PIO_DATA_OUT_BASE 0x20
#define PIO_DATA_OUT_SPAN 32
#define PIO_DATA_OUT_END 0x3f
#define PIO_DATA_OUT_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_DATA_OUT_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_DATA_OUT_CAPTURE 0
#define PIO_DATA_OUT_DATA_WIDTH 8
#define PIO_DATA_OUT_DO_TEST_BENCH_WIRING 0
#define PIO_DATA_OUT_DRIVEN_SIM_VALUE 0
#define PIO_DATA_OUT_EDGE_TYPE NONE
#define PIO_DATA_OUT_FREQ 50000000
#define PIO_DATA_OUT_HAS_IN 1
#define PIO_DATA_OUT_HAS_OUT 0
#define PIO_DATA_OUT_HAS_TRI 0
#define PIO_DATA_OUT_IRQ_TYPE NONE
#define PIO_DATA_OUT_RESET_VALUE 0

/*
 * Macros for device 'PIO_DATA_IN', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_DATA_IN_'.
 * The prefix is the slave descriptor.
 */
#define PIO_DATA_IN_COMPONENT_TYPE altera_avalon_pio
#define PIO_DATA_IN_COMPONENT_NAME PIO_DATA_IN
#define PIO_DATA_IN_BASE 0x30
#define PIO_DATA_IN_SPAN 32
#define PIO_DATA_IN_END 0x4f
#define PIO_DATA_IN_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_DATA_IN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_DATA_IN_CAPTURE 0
#define PIO_DATA_IN_DATA_WIDTH 8
#define PIO_DATA_IN_DO_TEST_BENCH_WIRING 0
#define PIO_DATA_IN_DRIVEN_SIM_VALUE 0
#define PIO_DATA_IN_EDGE_TYPE NONE
#define PIO_DATA_IN_FREQ 50000000
#define PIO_DATA_IN_HAS_IN 0
#define PIO_DATA_IN_HAS_OUT 1
#define PIO_DATA_IN_HAS_TRI 0
#define PIO_DATA_IN_IRQ_TYPE NONE
#define PIO_DATA_IN_RESET_VALUE 0

/*
 * Macros for device 'PIO_RESET', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_RESET_'.
 * The prefix is the slave descriptor.
 */
#define PIO_RESET_COMPONENT_TYPE altera_avalon_pio
#define PIO_RESET_COMPONENT_NAME PIO_RESET
#define PIO_RESET_BASE 0x40
#define PIO_RESET_SPAN 32
#define PIO_RESET_END 0x5f
#define PIO_RESET_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_RESET_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_RESET_CAPTURE 0
#define PIO_RESET_DATA_WIDTH 1
#define PIO_RESET_DO_TEST_BENCH_WIRING 0
#define PIO_RESET_DRIVEN_SIM_VALUE 0
#define PIO_RESET_EDGE_TYPE NONE
#define PIO_RESET_FREQ 50000000
#define PIO_RESET_HAS_IN 0
#define PIO_RESET_HAS_OUT 1
#define PIO_RESET_HAS_TRI 0
#define PIO_RESET_IRQ_TYPE NONE
#define PIO_RESET_RESET_VALUE 0

/*
 * Macros for device 'PIO_READ', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_READ_'.
 * The prefix is the slave descriptor.
 */
#define PIO_READ_COMPONENT_TYPE altera_avalon_pio
#define PIO_READ_COMPONENT_NAME PIO_READ
#define PIO_READ_BASE 0x50
#define PIO_READ_SPAN 32
#define PIO_READ_END 0x6f
#define PIO_READ_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_READ_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_READ_CAPTURE 0
#define PIO_READ_DATA_WIDTH 1
#define PIO_READ_DO_TEST_BENCH_WIRING 0
#define PIO_READ_DRIVEN_SIM_VALUE 0
#define PIO_READ_EDGE_TYPE NONE
#define PIO_READ_FREQ 50000000
#define PIO_READ_HAS_IN 0
#define PIO_READ_HAS_OUT 1
#define PIO_READ_HAS_TRI 0
#define PIO_READ_IRQ_TYPE NONE
#define PIO_READ_RESET_VALUE 0

/*
 * Macros for device 'PIO_WRITE', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_WRITE_'.
 * The prefix is the slave descriptor.
 */
#define PIO_WRITE_COMPONENT_TYPE altera_avalon_pio
#define PIO_WRITE_COMPONENT_NAME PIO_WRITE
#define PIO_WRITE_BASE 0x60
#define PIO_WRITE_SPAN 32
#define PIO_WRITE_END 0x7f
#define PIO_WRITE_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_WRITE_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_WRITE_CAPTURE 0
#define PIO_WRITE_DATA_WIDTH 1
#define PIO_WRITE_DO_TEST_BENCH_WIRING 0
#define PIO_WRITE_DRIVEN_SIM_VALUE 0
#define PIO_WRITE_EDGE_TYPE NONE
#define PIO_WRITE_FREQ 50000000
#define PIO_WRITE_HAS_IN 0
#define PIO_WRITE_HAS_OUT 1
#define PIO_WRITE_HAS_TRI 0
#define PIO_WRITE_IRQ_TYPE NONE
#define PIO_WRITE_RESET_VALUE 0

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x10000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x10007
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1562154332

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x20000
#define JTAG_UART_SPAN 16
#define JTAG_UART_END 0x2000f
#define JTAG_UART_IRQ 2
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


#endif /* _ALTERA_HPS_0_H_ */
